# Generated by Django 3.0.3 on 2020-02-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_prodid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodid',
        ),
    ]
