# Generated by Django 3.0.3 on 2020-02-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200227_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
